HumanSignal/label-studio-ml-backend

- label_studio_ml/default_configs/Dockerfile
Hi Heartexlabs,
I have been playing around with the ML backend, thank you very much for this great backend.
I would like to contribute to the project with a small rewriting of the Dockerfile. Hope you find it worth for the project.
Cheers,
Manuel
> Dockerfile rewrite

- label_studio_ml/api.py
Fixing error 404 when trying to visit /  by adding route to /health
> Fixing error 404 when trying to visit /

- label_studio_ml/utils.py
> To retrieve the project id for the proper filepath

- README.md
> Updated the correct path for the example in readme

- label_studio_ml/model.py
See https://github.com/heartexlabs/label-studio-ml-backend/issues/79
> [fix] CUDA with multiprocessing

- label_studio_ml/model.py
> fix: DEV-1777: Change error OSError to warning when result file not found

- label_studio_ml/examples/huggingface/Dockerfile
- label_studio_ml/examples/huggingface/README.md
- label_studio_ml/examples/huggingface/_wsgi.py
- label_studio_ml/examples/huggingface/docker-compose.yml
- label_studio_ml/examples/huggingface/requirements.txt
- label_studio_ml/examples/huggingface/supervisord.conf
- label_studio_ml/examples/huggingface/uwsgi.ini
Fix huggingface blog post example requirements
Add default docker compose
> [fix] Fix huggingface blog post example

- label_studio_ml/examples/dummy_model/_wsgi.py
Just reading through and caught this typo.
> Fix false casting

- label_studio_ml/examples/tesseract/README.md
- label_studio_ml/examples/tesseract/requirements.txt
- label_studio_ml/examples/tesseract/tesseract.py
Added an adapted example using interactive OCR (here using Tesseract) when drawing a box.
It can help speed up OCR annotation (for both detection and recognition) and can be used along with static pre-annotations
> bbox Interactive OCR Demo using Tesseract

- label_studio_ml/examples/bert/_wsgi.py
- label_studio_ml/examples/bert/bert_classifier.py
- label_studio_ml/examples/dummy_model/_wsgi.py
- label_studio_ml/examples/electra/_wsgi.py
- label_studio_ml/examples/electra/electra.py
- label_studio_ml/examples/flair/_wsgi.py
- label_studio_ml/examples/huggingface/_wsgi.py
- label_studio_ml/examples/mmdetection/_wsgi.py
- label_studio_ml/examples/nemo/_wsgi.py
- label_studio_ml/examples/ner/_wsgi.py
- label_studio_ml/examples/pytorch_transfer_learning/_wsgi.py
- label_studio_ml/examples/simple_text_classifier/_wsgi.py
- label_studio_ml/examples/substring_matching/_wsgi.py
- label_studio_ml/examples/tensorflow/_wsgi.py
- label_studio_ml/examples/tesseract/_wsgi.py
- label_studio_ml/examples/the_simplest_backend/_wsgi.py
- label_studio_ml/tests/test_basic.py
- Missing JSON imports added
- bad test deleted
- reset_model assigns to self.model
- MODEL_FILE used properly
PR requested in #137
> Various fixes (missing imports; bad test; reset_model no-op; misused global)

- label_studio_ml/examples/easyocr/.dockerignore
- label_studio_ml/examples/easyocr/Dockerfile
- label_studio_ml/examples/easyocr/README.md
- label_studio_ml/examples/easyocr/_wsgi.py
- label_studio_ml/examples/easyocr/docker-compose.yml
- label_studio_ml/examples/easyocr/easyocr_labeling.py
- label_studio_ml/examples/easyocr/requirements.txt
- label_studio_ml/examples/easyocr/supervisord.conf
- label_studio_ml/examples/easyocr/uwsgi.ini
Added EASY OCR machine learning model to auto-detect all the text bou…nding polygons and perform OCR. =]
> Added EASYOCR machine learning model

- label_studio_ml/examples/mmdetection/mmdetection.py
need to provide a parameter endpoint_url similar to device in label-studio-ml launch
LABEL_STUDIO_HOSTNAME=http://label-studio-address:8080 \ label-studio-ml start coco-detector --port PORT --with \ config_file=/home/testuser/share/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \ checkpoint_file=/home/testuser/share/mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \ device=cuda:0 endpoint_url=<your s3 endpoint url>
> fixed problem with s3 where endpoint_url was missing

- .github/workflows/tests.yml
Use python3-dev package instead of removed python-dev
> ci: Switch to python3-dev package

- label_studio_ml/model.py
> change AUTO_UPDATE_DEFAULT to False

- label_studio_ml/examples/pytorch_transfer_learning/pytorch_transfer_learning.py
Update image classification model training in fit function since completions is removed after Label Studio 1.5.0 .
> NOTE
The completions field is deprecated as of Label Studio 1.0.x. In version 1.5.0 it will be removed. Instead, use the SDK or the API to retrieve annotation and task data using annotation and task IDs. See [trigger training with webhooks](https://labelstud.io/guide/ml_create.html#Trigger-training-with-webhooks) for more details.
From [Link](https://labelstud.io/guide/ml_create.html#Train-a-model-with-your-ML-backend).
Fix similar problem as ISSUE #118 .
> fix: Update image classification model training in fit function since completions is removed.

- .github/workflows/tests.yml
- label_studio_ml/examples/easyocr/Dockerfile
- label_studio_ml/examples/mmdetection/Dockerfile
- label_studio_ml/examples/segment_anything_model/docker-compose.yml
- label_studio_ml/examples/segment_anything_model/segment_anything_model.py
This PR adds fixes to address ML Model tests which were implicitly failing (because they were not being run regularly). It also adds a change to CI so while we keep selective running of tests in PR branches on changes, we will now run all tests on merge to master and release branches.
> fix: breaking ml model tests

- label_studio_ml/examples/segment_anything_model/README.md
docker compse -> docker compose
> Fix typo in instructions for running SAM

- label_studio_ml/examples/yolov8/model.py
Allows for batch training tasks when using YOLO
> Add batching support in fit method

- label_studio_ml/examples/grounding_dino/README.md
- label_studio_ml/examples/grounding_dino/dino.py
- label_studio_ml/examples/grounding_dino/docker-compose.yml
1. `labels` are not populated in prompted predictions - you have to assign them manually
2. fix bug when GroundingDINO can only be used with "$image" object key
3. cleanup code styling and variables
4. fix inference run on GPU
5. fix default variables for `USE_SAM` and `USE_MOBILE_SAM`
> fix: LEAP-932: Having pulled suggestions from ML backend causes validation on Labeling Interface

- label_studio_ml/examples/bert_classifier/README.md
- label_studio_ml/examples/easyocr/README.md
- label_studio_ml/examples/flair/README.md
- label_studio_ml/examples/gliner/README.md
- label_studio_ml/examples/grounding_dino/README.md
- label_studio_ml/examples/huggingface_llm/README.md
- label_studio_ml/examples/huggingface_ner/README.md
- label_studio_ml/examples/interactive_substring_matching/README.md
- label_studio_ml/examples/langchain_search_agent/README.md
- label_studio_ml/examples/llm_interactive/README.md
- label_studio_ml/examples/mmdetection-3/README.md
- label_studio_ml/examples/nemo_asr/README.md
- label_studio_ml/examples/segment_anything_model/README.md
- label_studio_ml/examples/sklearn_text_classifier/README.md
- label_studio_ml/examples/spacy/README.md
- label_studio_ml/examples/tesseract/README.md
Working through some styling changes with @huguestennier, so updating the frontmatter of the readme docs
> docs: Updating frontmatter for styling changes

- label_studio_ml/examples/bert_classifier/model.py
- label_studio_ml/examples/flair/model.py
- label_studio_ml/examples/huggingface_llm/model.py
- label_studio_ml/examples/huggingface_ner/model.py
- label_studio_ml/examples/interactive_substring_matching/model.py
- label_studio_ml/examples/langchain_search_agent/model.py
- label_studio_ml/examples/llm_interactive/model.py
- label_studio_ml/examples/sklearn_text_classifier/model.py
- label_studio_ml/examples/spacy/model.py
- label_studio_ml/model.py
- label_studio_ml/utils.py
- tests/test_unit_model.py
Use get_local_path() for task data if valueType=url.
> fix: RND-71: Support cloud storage links resolution for textual ML backends

- label_studio_ml/examples/llm_interactive/README.md
- label_studio_ml/examples/llm_interactive/docker-compose.yml
- label_studio_ml/examples/llm_interactive/model.py
Added support for [Ollama](ollama.com) in LLM Interactive example. Details for connecting to Ollama are detailed in the Readme.
> Added support for Ollama in LLM Interactive example

- label_studio_ml/examples/mmdetection-3/README.md
> Fix codeblock indents in readme mmdetection-3

- label_studio_ml/examples/langchain_search_agent/Dockerfile
- label_studio_ml/examples/spacy/Dockerfile
- label_studio_ml/examples/spacy/requirements.txt
It's a python 3.12.4 problem. The temporary solution is to downgrade to 3.12.3.
https://stackoverflow.com/a/78598900/1045399
> fix: Spacy pydantic deps

- label_studio_ml/examples/llm_interactive/README.md
Updating LLM interactive example with Ollama in frontmatter
> docs: Add Ollama to LLM interactive frontmatter

- label_studio_ml/examples/grounding_sam/README.md
- label_studio_ml/examples/segment_anything_2_image/README.md
- label_studio_ml/examples/segment_anything_2_video/README.md
- label_studio_ml/examples/tesseract/README.md
- label_studio_ml/examples/watsonx_llm/README.md
Adding front matter to new README files and making small fixes to ensure these work in the tutorials page in the docs
> docs: Fixes and adding front matter to example README files

- label_studio_ml/examples/segment_anything_2_image/README.md
- label_studio_ml/examples/segment_anything_2_video/README.md
- label_studio_ml/examples/watsonx_llm/README.md
Making small changes to the new readme files so that they format better in the docs site
> docs: ReadMe updates for tutorials
